// <auto-generated />
using KPIAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KPIAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231208020601_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KPIAPI.Data.Models.Department", b =>
                {
                    b.Property<int>("DepNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepNo"));

                    b.HasKey("DepNo");

                    b.ToTable("TblDepartmants", (string)null);
                });

            modelBuilder.Entity("KPIAPI.Data.Models.KPI", b =>
                {
                    b.Property<int>("KPIIDNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KPIIDNum"));

                    b.Property<int>("DepNo")
                        .HasColumnType("int");

                    b.Property<string>("KPIDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MeasurementUnit")
                        .HasColumnType("bit");

                    b.Property<int>("TargetedValue")
                        .HasColumnType("int");

                    b.HasKey("KPIIDNum");

                    b.HasIndex("DepNo");

                    b.ToTable("TblKPI", (string)null);
                });

            modelBuilder.Entity("KPIAPI.Data.Models.KPI", b =>
                {
                    b.HasOne("KPIAPI.Data.Models.Department", "Dep")
                        .WithMany("KPIs")
                        .HasForeignKey("DepNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dep");
                });

            modelBuilder.Entity("KPIAPI.Data.Models.Department", b =>
                {
                    b.Navigation("KPIs");
                });
#pragma warning restore 612, 618
        }
    }
}
